[axum]
host = "0.0.0.0"
port = 8888

[db]
host = "db"
port = 5432
dbname = "cdsctf"
username = "cdsctf"
password = "cdsctf"
sslmode = "disable"

[queue]
host = "queue"
port = 4222
token = ""
user = ""
password = ""
tls = false

[cache]
url = "redis://192.168.206.129:6379/1"

[metric]
enabled = false
namespace = "cdsctf"