[package]
name = "cds-config"
version = "0.0.1"
edition = "2024"
publish = false
resolver = "2"

[dependencies]
once_cell = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
toml = { workspace = true }

[lib]
path = "src/lib.rs"
