version: "3.0"
services:
    core:
        image: elabosak233/cloudsdale:main
        restart: always
        ports:
            - "8888:8888"
        volumes:
            - "./application.yml:/app/application.yml:ro"
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./captures:/app/captures"
            - "./media:/app/media"
            - "./logs:/app/logs"
        depends_on:
            - db

    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_USER: cloudsdale
            MYSQL_PASSWORD: cloudsdale
            MYSQL_DATABASE: cloudsdale
            MYSQL_ROOT_PASSWORD: cloudsdale
        volumes:
            - "./db:/var/lib/mysql"
