version: "3.0"
services:
    core:
        image: elabosak233/cloudsdale:main
        restart: always
        ports:
            - "8888:8888"
        volumes:
            - "./application.yml:/app/application.yml:ro"
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./assets:/app/assets"
            - "./captures:/app/captures"
            - "./media:/app/media"
            - "./logs:/app/logs"
        depends_on:
            - db

    db:
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_USER: cloudsdale
            POSTGRES_PASSWORD: cloudsdale
            POSTGRES_DB: cloudsdale
        volumes:
            - "./db:/var/lib/postgresql/data"
