apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority: /path/to/ca.crt
      server: https://127.0.0.1:8443
    name: cloudsdale-cluster
contexts:
  - context:
      cluster: cloudsdale-cluster
      user: cloudsdale
    name: cloudsdale-context
current-context: cloudsdale-context
users:
  - name: cloudsdale
    user:
      client-certificate: /path/to/client.crt
      client-key: /path/to/client.key