services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: cdsctf
      POSTGRES_PASSWORD: cdsctf
      POSTGRES_DB: cdsctf
    ports:
      - "${CDSCTF_DEV_DB_PORT:-5432}:5432"
    volumes:
      - db:/var/lib/postgresql/18/docker

  cache:
    image: valkey/valkey:9-alpine
    restart: unless-stopped
    ports:
      - "${CDSCTF_DEV_CACHE_PORT:-6379}:6379"
    volumes:
      - cache:/data

  queue:
    image: nats:2-alpine
    restart: unless-stopped
    ports:
      - "${CDSCTF_DEV_QUEUE_PORT:-4222}:4222"   # client
      - "${CDSCTF_DEV_QUEUE_MONITOR_PORT:-8222}:8222"   # HTTP monitoring
    volumes:
      - queue:/data
    command: ["--jetstream", "-sd", "/data", "-m", "8222"]

  media:
    image: rustfs/rustfs:latest
    restart: unless-stopped
    ports:
      - "${CDSCTF_DEV_MEDIA_PORT:-9000}:9000"
      - "${CDSCTF_DEV_MEDIA_CONSOLE_PORT:-9001}:9001"
    volumes:
      - media:/data

volumes:
  db:
  cache:
  queue:
  media:
