[package]
name = "cds-metric"
version = "0.0.1"
edition = "2024"
publish = false
resolver = "2"

[dependencies]
cds-config = { workspace = true }

prometheus = { workspace = true }
once_cell = { workspace = true }