site_name: Cloudsdale

repo_url: https://github.com/elabosak233/cloudsdale
repo_name: elabosak233/cloudsdale

docs_dir: pages

theme:
  name: material
  language: zh
  logo: assets/favicon.ico
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: custom
  font:
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.indexes

extra_css:
  - stylesheets/extra.css

plugins: 
  - glightbox

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - 简介: index.md
  - 部署:
    - Docker: deploy/docker.md
    - Docker + K8s: deploy/docker-k8s.md
    - K8s: deploy/k8s.md
  - 配置:
    - config/index.md
    - 数据库: config/database.md
    - 缓存: config/cache.md
    - 代理与流量捕获: config/proxy/index.md
  - 题目: challenge/index.md
  - 比赛: game/index.md
  - FAQ: faq/index.md