definitions:
  request.InstanceCreateRequest:
    properties:
      challenge_id:
        type: string
    required:
    - challenge_id
    type: object
  request.UserLoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  request.UserLogoutRequest:
    properties:
      username:
        type: string
    required:
    - username
    type: object
  request.UserRegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
info:
  contact: {}
  description: 没有其他东西啦，仅仅是所有的后端接口，不要乱用哦
  title: PgsHub Backend API
  version: "1.0"
paths:
  /api/instance/create:
    post:
      consumes:
      - application/json
      description: 创建实例
      parameters:
      - description: InstanceCreateRequest
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.InstanceCreateRequest'
      produces:
      - application/json
      responses: {}
      summary: 创建实例
      tags:
      - 实例
  /api/instance/remove:
    get:
      description: 停止并删除容器
      parameters:
      - description: InstanceId
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 停止并删除容器
      tags:
      - 实例
  /api/instance/renew:
    get:
      description: 容器续期
      parameters:
      - description: InstanceId
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 容器续期
      tags:
      - 实例
  /api/instance/status:
    get:
      description: 获取示例状态
      parameters:
      - description: InstanceId
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 获取示例状态
      tags:
      - 实例
  /api/user/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: UserLoginRequest
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.UserLoginRequest'
      produces:
      - application/json
      responses: {}
      summary: 用户登录
      tags:
      - 用户
  /api/user/logout:
    post:
      consumes:
      - application/json
      description: 用户登出
      parameters:
      - description: UserLogoutRequest
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.UserLogoutRequest'
      produces:
      - application/json
      responses: {}
      summary: 用户登出
      tags:
      - 用户
  /api/user/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: UserRegisterRequest
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/request.UserRegisterRequest'
      produces:
      - application/json
      responses: {}
      summary: 用户注册
      tags:
      - 用户
  /api/user/verifyToken/{token}:
    get:
      description: Token 鉴定
      parameters:
      - description: token
        in: path
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Token 鉴定
      tags:
      - 用户
swagger: "2.0"
