[package]
name = "cds-server"
resolver = "3"

authors = { workspace = true }
edition  = { workspace = true }
homepage = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
cds-assets = { workspace = true }
cds-config = { workspace = true }
cds-db = { workspace = true }
cds-cluster = { workspace = true }
cds-queue = { workspace = true }
cds-web = { workspace = true }
cds-cache = { workspace = true }
cds-checker = { workspace = true }
cds-telemetry = { workspace = true }
cds-email = { workspace = true }
cds-logger = { workspace = true }

tracing = { workspace = true }
tokio = { workspace = true }
rustls = { workspace = true }
axum = { workspace = true }
sea-orm = { workspace = true }
argon2 = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }

[[bin]]
name = "cdsctf"
path = "src/main.rs"